export const searchTermPlaceholderCopy = 'Search'
export const signinButtonCopy = 'Signin'
export const feedbackPageCopy = 'Feedback'
export const onlineBankingPageCopy = 'Online Banking'
export const homePageCopy = 'Online Banking'
export const onlineBankingTitleCopy = 'Online Banking'
export const checkingAccountActivityTitleCopy = 'Checking Account Activity'
export const transferFundsTitleCopy = 'Transfer Funds'
export const myMoneyMapTitleCopy = 'My Money Map'
export const onlineBankingTitleDescriptionCopy = 'Click the button below to view online banking features.'
export const checkingAccountActivityTitleDescriptionCopy = 'Use Zero to view the most up-to-date listings of your deposits, withdrawals, interest payments, and a number of other useful transactions.'
export const transferFundsTitleDescriptionCopy = 'Use Zero to safely and securely transfer funds between accounts. There is no hold placed on online money transfers, so your funds are available when you need them.'
export const myMoneyMapTitleDescriptionCopy = 'Use Zero to set up and monitor your personalized money map. A money map is an easy-to-use online tool that helps you manage your finances efficiently. With Money Map, you can create a budget, sort your finances into spending and savings categories, check the interest your accounts are earning, and gain new understanding of your patterns with the help of Zero’s clear charts and graphs.'
export const moreServicesButtonCopy = 'More Services'

// search
export const searchResultsTitleCopy = 'Search Results:'
export const searchResultsOneCopy = 'Zero - Personal Banking - Loans - Credit Cards'
export const searchResultsTwoCopy = 'Zero - Free Access to Online Banking'
export const searchResultsThreeCopy = ''
export const searchResultsFourCopy = ''
export const searchResultsFiveCopy = ''

// carrousel
export const carrouselImageOneSRC = '/resources/img/main_carousel_1.jpg'
export const carrouselImageTwoSRC = '/resources/img/main_carousel_2.jpg'
export const carrouselImageThreeSRC = '/resources/img/main_carousel_3.jpg'
export const carrouselTitleCopy = 'Online Banking'
export const carrouselDescriptionCopy = 'Welcome to Zero Online Banking. Zero provides a greener and more convenient way to manage your money. Zero enables you to check your account balances, pay your bills, transfer money, and keep detailed records of your transactions, wherever there is an internet connection.'

// online banking tab
export const onlineBankingSubtitleCopy = 'Pay bills easily'
export const adDescriptionCopy = 'Our Bank is trusted by over 1,000,000 customers world wide. Sign in now!'
export const adDescriptionLinkCopy = 'Sign in'
export const accountSummaryLinkCopy = 'Account Summary'
export const accountSummaryDescriptionCopy = 'See all of your account balances at a glance.'
export const accountActivityLinkCopy = 'Account Activity'
export const accountActivityDescriptionCopy = 'View the most up-to-date listings of your deposits, withdrawals, interest payments, and other transactions.'
export const transferFundsLinkCopy = 'Transfer Funds'
export const transferFundsDescriptionCopy = 'Safely and securely transfer funds between accounts.'
export const payBillsLinkCopy = 'Pay Bills'
export const payBillsDescriptionCopy = 'Pay your bills quickly and securely online.'
export const myMoneyMapLinkCopy = 'My Money Map'
export const onlineBankingMyMoneyMapTitleDescriptionCopy = 'Use Zero to set up and monitor your personalized money map. A money map is an easy-to-use online tool that helps you manage your finances efficiently.'
export const onlineStatementsLinkCopy = 'Online Statements'
export const onlineStatementsDescriptionCopy = 'View the statement history of all your accounts.'

// footer
export const disclaimerTextCopy = 'The Free Online Bank Web site is published by Micro Focus Fortify for the sole purpose of demonstrating the functionality and effectiveness of Micro Focus Fortify’s WebInspect products in detecting and reporting Web application vulnerabilities. This site is not a real banking site and any similarities to third party products and/or Web sites are purely coincidental. This site is provided "as is" without warranty of any kind, either express or implied. Micro Focus Fortify does not assume any risk in relation to your use of this Web site. Use of this Web site indicates that you have read and agree to Micro Focus Fortify’s Terms of Use found at'
export const disclaimerTextCopyrightCopy = 'Copyright © 2012-2018, Micro Focus Development Company. All rights reserved.'
export const disclaimerLinkOneCopy = 'https://www.microfocus.com/about/legal/#privacy'
export const disclaimerLinkTwoCopy = 'https://www.microfocus.com/about/legal/#privacy'
