export const signinButton = '#signin_button'
export const searchTerm = '#searchTerm'
export const feedbackPage = '#feedback'
export const numberOfLinks = 'li > a'
export const homeMenu = '#homeMenu'
export const onlineBankingMenu = '#onlineBankingMenu'
export const feedbackMenu = '#feedback'
export const onlineBankingIcon = '#online_banking_features > div:nth-child(1) > h4 > i'
export const onlineBankingLink = '#online_banking_features > div:nth-child(1) > h4'
export const onlineBankingDescription = '#online_banking_features > div:nth-child(1) > p'
export const checkingAccountActivityIcon = '#account_activity_link > i'
export const checkingAccountActivityLink = '#account_activity_link'
export const checkingAccountActivityDescription = '#online_banking_features > div:nth-child(2) > div > p'
export const transferFundsIcon = '#transfer_funds_link > i'
export const transferFundsLink = '#transfer_funds_link'
export const transferFundsDescription = '#online_banking_features > div:nth-child(3) > div > p'
export const myMoneyMapIcon = '#money_map_link > i'
export const myMoneyMapLink = '#money_map_link'
export const myMoneyMapDescription = '#online_banking_features > div:nth-child(4) > div > p'
export const moreServicesButton = '#online-banking'
export const zeroBankLogoButton = 'body > div.wrapper > div.navbar.navbar-fixed-top > div > div > a'

// search
export const searchResultsTitle = 'body > div.wrapper > div.container > div > h2'
export const searchResultsOne = 'body > div.wrapper > div.container > div > ul > li:nth-child(1) > a'
export const searchResultsTwo = 'body > div.wrapper > div.container > div > ul > li:nth-child(2) > a'
export const searchResultsThree = 'body > div.wrapper > div.container > div > ul > li:nth-child(3) > a'
export const searchResultsFour = 'body > div.wrapper > div.container > div > ul > li:nth-child(4) > a'
export const searchResultsFive = 'body > div.wrapper > div.container > div > ul > li:nth-child(5) > a'

// carrousel
export const carrouselFreshImage = '#carousel > div > div.active.item > img'
export const carrouselChangedImage = '#carousel > div > div.item.active > img'
export const carrouselControlRight = '#carousel > a.carousel-control.custom.right'
export const carrouselControlLeft = '#carousel > a.carousel-control.custom.left'
export const carrouselTitle = '#carousel > div > div.active.item > div > h4'
export const carrouselDescription = '#carousel > div > div.active.item > div > p'

// online banking tab
export const onlineBankingTitle = 'body > div.wrapper > div.container > div > div:nth-child(2) > div > div > div > div > div > h1'
export const onlineBankingSubtitle = 'body > div.wrapper > div.container > div > div:nth-child(2) > div > div > div > div > div > p'
export const adDescription = 'body > div.wrapper > div.container > div > div:nth-child(3) > div > h3'
export const adDescriptionLink = 'body > div.wrapper > div.container > div > div:nth-child(3) > div > h3 > a'
export const accountSummaryIcon = '.icon-list-alt'
export const accountSummaryLink = '#account_summary_link'
export const accountSummaryDescription = '#online_banking_features > div:nth-child(1) > div:nth-child(1) > p'
export const accountActivityIcon = '.icon-shopping-cart'
export const accountActivityLink = '#account_activity_link'
export const accountActivityDescription = '#online_banking_features > div:nth-child(1) > div:nth-child(2) > p'
export const onlineBankingTransferFundsIcon = '.icon-retweet'
export const onlineBankingTransferFundsDescription = '#online_banking_features > div:nth-child(1) > div:nth-child(3) > p'
export const payBillsIcon = '.icon-credit-card'
export const payBillsLink = '#pay_bills_link'
export const payBillsDescription = '#online_banking_features > div:nth-child(2) > div:nth-child(1) > p'
export const onlineBankingMyMoneyMapIcon = '.icon-sitemap'
export const onlineBankingMyMoneyMapDescription = '#online_banking_features > div:nth-child(2) > div:nth-child(2) > p'
export const onlineStatementsIcon = '.icon-edit'
export const onlineStatementsLink = '#online_statements_link'
export const onlineStatementsDescription = '#online_banking_features > div:nth-child(2) > div:nth-child(3) > p'

// footer
export const footer = 'body > div.extra'
export const downloadWebInspectLink = '#download_webinspect_link'
export const termsOfUseLink = '#terms_of_use_link'
export const contactMicroFocusLink = '#contact_hp_link'
export const privacyStatementLink = '#privacy_statement_link'
export const disclaimerText = 'body > div.extra > div > div > div:nth-child(2) > div'
export const disclaimerLinkOne = 'body > div.extra > div > div > div:nth-child(2) > div > a:nth-child(1)'
export const disclaimerLinkTwo = 'body > div.extra > div > div > div:nth-child(2) > div > a:nth-child(2)'