export const loginPageTitle = 'body > div.wrapper > div.container > div > div > div > div > h3'
export const signinButton = '#signin_button'
export const username = '#user_login'
export const password = '#user_password'
export const submitButton = 'input[type="submit"]'
export const errorMessage = '#login_form > div.alert.alert-error'
export const rememberMeCheckbox = '#user_remember_me'
export const resetPasswordLink = 'body > div.wrapper > div.container > div > div > div > a'
export const loginLabel = 'label[for="user_login"]'
export const passwordLabel = 'label[for="user_password"]'
export const rememberMeLabel = 'label[for="user_remember_me"]'
export const usernameButtonLink = '#settingsBox > ul > li:nth-child(3) > a'
export const logoutButton = '#logout_link'