export const transferFundsPageTitle = '#transfer_funds_content > form > div > div > h2'
export const transferFundsConfirmPageTitle = '#transfer_funds_content > div > div > h2'
export const transferFundsDescription = '#transfer_funds_content > form > div > div > div.board > div > p'
export const fromAccount = '#tf_fromAccountId'
export const toAccount = '#tf_toAccountId'
export const amount = '#tf_amount'
export const description = '#tf_description'
export const continueButton = 'button[type="submit"]'
export const cancelButton = '#btn_cancel'
export const submitButton = '#btn_submit'
export const successMessage = '.alert-success'
export const makeAnotherTransferButtonLink = '#transfer_funds_content > div > a'
export const fromAccountConfirmPage = '#transfer_funds_content > div > div > div.board > div > div:nth-child(1) > div.span3'
export const toAccountConfirmPage = '#transfer_funds_content > div > div > div.board > div > div:nth-child(2) > div.span3'
export const amountConfirmPage = '#transfer_funds_content > div > div > div.board > div > div:nth-child(3) > div.span3'
export const descriptionAdditionalInfo = '#transfer_funds_content > form > div > div > div.board > div > article > fieldset > div:nth-child(6) > div > p'
